version: "3.8"
services:

  secta:
    build: .
    ports:
      - "666:666"
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_NAME=secta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=avesatan666
      - POSTGRES_PORT=5432
    restart: always
    # volumes:
      # - ./postgres-data:/var/lib/postgresql/data
