# Generated by Django 3.2.4 on 2022-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsekte_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sektant',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
